// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nebulapb.proto

package nebulapb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerEntryStream_Type int32

const (
	ServerEntryStream_SYNC   ServerEntryStream_Type = 0
	ServerEntryStream_REMOVE ServerEntryStream_Type = 1
)

var ServerEntryStream_Type_name = map[int32]string{
	0: "SYNC",
	1: "REMOVE",
}

var ServerEntryStream_Type_value = map[string]int32{
	"SYNC":   0,
	"REMOVE": 1,
}

func (x ServerEntryStream_Type) String() string {
	return proto.EnumName(ServerEntryStream_Type_name, int32(x))
}

func (ServerEntryStream_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{0, 0}
}

type BungeeEntryStream_Type int32

const (
	BungeeEntryStream_SYNC BungeeEntryStream_Type = 0
)

var BungeeEntryStream_Type_name = map[int32]string{
	0: "SYNC",
}

var BungeeEntryStream_Type_value = map[string]int32{
	"SYNC": 0,
}

func (x BungeeEntryStream_Type) String() string {
	return proto.EnumName(BungeeEntryStream_Type_name, int32(x))
}

func (BungeeEntryStream_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{10, 0}
}

// ServerEntryStream (type: sync, remove)
type ServerEntryStream struct {
	Type                 ServerEntryStream_Type `protobuf:"varint,1,opt,name=type,proto3,enum=nebulapb.ServerEntryStream_Type" json:"type,omitempty"`
	Entry                *ServerEntry           `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ServerEntryStream) Reset()         { *m = ServerEntryStream{} }
func (m *ServerEntryStream) String() string { return proto.CompactTextString(m) }
func (*ServerEntryStream) ProtoMessage()    {}
func (*ServerEntryStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{0}
}

func (m *ServerEntryStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerEntryStream.Unmarshal(m, b)
}
func (m *ServerEntryStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerEntryStream.Marshal(b, m, deterministic)
}
func (m *ServerEntryStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerEntryStream.Merge(m, src)
}
func (m *ServerEntryStream) XXX_Size() int {
	return xxx_messageInfo_ServerEntryStream.Size(m)
}
func (m *ServerEntryStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerEntryStream.DiscardUnknown(m)
}

var xxx_messageInfo_ServerEntryStream proto.InternalMessageInfo

func (m *ServerEntryStream) GetType() ServerEntryStream_Type {
	if m != nil {
		return m.Type
	}
	return ServerEntryStream_SYNC
}

func (m *ServerEntryStream) GetEntry() *ServerEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type ServerEntry struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string        `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Address              string        `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port                 int32         `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Motd                 string        `protobuf:"bytes,5,opt,name=motd,proto3" json:"motd,omitempty"`
	Fallback             bool          `protobuf:"varint,6,opt,name=fallback,proto3" json:"fallback,omitempty"`
	Lockdown             *Lockdown     `protobuf:"bytes,7,opt,name=lockdown,proto3" json:"lockdown,omitempty"`
	Status               *ServerStatus `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServerEntry) Reset()         { *m = ServerEntry{} }
func (m *ServerEntry) String() string { return proto.CompactTextString(m) }
func (*ServerEntry) ProtoMessage()    {}
func (*ServerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{1}
}

func (m *ServerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerEntry.Unmarshal(m, b)
}
func (m *ServerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerEntry.Marshal(b, m, deterministic)
}
func (m *ServerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerEntry.Merge(m, src)
}
func (m *ServerEntry) XXX_Size() int {
	return xxx_messageInfo_ServerEntry.Size(m)
}
func (m *ServerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ServerEntry proto.InternalMessageInfo

func (m *ServerEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerEntry) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ServerEntry) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServerEntry) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerEntry) GetMotd() string {
	if m != nil {
		return m.Motd
	}
	return ""
}

func (m *ServerEntry) GetFallback() bool {
	if m != nil {
		return m.Fallback
	}
	return false
}

func (m *ServerEntry) GetLockdown() *Lockdown {
	if m != nil {
		return m.Lockdown
	}
	return nil
}

func (m *ServerEntry) GetStatus() *ServerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type Lockdown struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lockdown) Reset()         { *m = Lockdown{} }
func (m *Lockdown) String() string { return proto.CompactTextString(m) }
func (*Lockdown) ProtoMessage()    {}
func (*Lockdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{2}
}

func (m *Lockdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lockdown.Unmarshal(m, b)
}
func (m *Lockdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lockdown.Marshal(b, m, deterministic)
}
func (m *Lockdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lockdown.Merge(m, src)
}
func (m *Lockdown) XXX_Size() int {
	return xxx_messageInfo_Lockdown.Size(m)
}
func (m *Lockdown) XXX_DiscardUnknown() {
	xxx_messageInfo_Lockdown.DiscardUnknown(m)
}

var xxx_messageInfo_Lockdown proto.InternalMessageInfo

func (m *Lockdown) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Lockdown) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ServerStatus struct {
	Online  bool                  `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	Version *ServerStatus_Version `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Players *ServerStatus_Players `protobuf:"bytes,3,opt,name=players,proto3" json:"players,omitempty"`
	// i don't have any idea... (need map)
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Favicon              string   `protobuf:"bytes,5,opt,name=favicon,proto3" json:"favicon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStatus) Reset()         { *m = ServerStatus{} }
func (m *ServerStatus) String() string { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()    {}
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{3}
}

func (m *ServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus.Unmarshal(m, b)
}
func (m *ServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus.Marshal(b, m, deterministic)
}
func (m *ServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus.Merge(m, src)
}
func (m *ServerStatus) XXX_Size() int {
	return xxx_messageInfo_ServerStatus.Size(m)
}
func (m *ServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus proto.InternalMessageInfo

func (m *ServerStatus) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *ServerStatus) GetVersion() *ServerStatus_Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ServerStatus) GetPlayers() *ServerStatus_Players {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *ServerStatus) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ServerStatus) GetFavicon() string {
	if m != nil {
		return m.Favicon
	}
	return ""
}

type ServerStatus_Version struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol             int32    `protobuf:"varint,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStatus_Version) Reset()         { *m = ServerStatus_Version{} }
func (m *ServerStatus_Version) String() string { return proto.CompactTextString(m) }
func (*ServerStatus_Version) ProtoMessage()    {}
func (*ServerStatus_Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{3, 0}
}

func (m *ServerStatus_Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus_Version.Unmarshal(m, b)
}
func (m *ServerStatus_Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus_Version.Marshal(b, m, deterministic)
}
func (m *ServerStatus_Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus_Version.Merge(m, src)
}
func (m *ServerStatus_Version) XXX_Size() int {
	return xxx_messageInfo_ServerStatus_Version.Size(m)
}
func (m *ServerStatus_Version) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus_Version.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus_Version proto.InternalMessageInfo

func (m *ServerStatus_Version) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerStatus_Version) GetProtocol() int32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

type ServerStatus_Players struct {
	Max                  int32    `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	Online               int32    `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerStatus_Players) Reset()         { *m = ServerStatus_Players{} }
func (m *ServerStatus_Players) String() string { return proto.CompactTextString(m) }
func (*ServerStatus_Players) ProtoMessage()    {}
func (*ServerStatus_Players) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{3, 1}
}

func (m *ServerStatus_Players) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStatus_Players.Unmarshal(m, b)
}
func (m *ServerStatus_Players) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStatus_Players.Marshal(b, m, deterministic)
}
func (m *ServerStatus_Players) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStatus_Players.Merge(m, src)
}
func (m *ServerStatus_Players) XXX_Size() int {
	return xxx_messageInfo_ServerStatus_Players.Size(m)
}
func (m *ServerStatus_Players) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStatus_Players.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStatus_Players proto.InternalMessageInfo

func (m *ServerStatus_Players) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *ServerStatus_Players) GetOnline() int32 {
	if m != nil {
		return m.Online
	}
	return 0
}

//
// ServerEntry
//
type GetServerEntryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServerEntryRequest) Reset()         { *m = GetServerEntryRequest{} }
func (m *GetServerEntryRequest) String() string { return proto.CompactTextString(m) }
func (*GetServerEntryRequest) ProtoMessage()    {}
func (*GetServerEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{4}
}

func (m *GetServerEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServerEntryRequest.Unmarshal(m, b)
}
func (m *GetServerEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServerEntryRequest.Marshal(b, m, deterministic)
}
func (m *GetServerEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServerEntryRequest.Merge(m, src)
}
func (m *GetServerEntryRequest) XXX_Size() int {
	return xxx_messageInfo_GetServerEntryRequest.Size(m)
}
func (m *GetServerEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServerEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServerEntryRequest proto.InternalMessageInfo

type GetServerEntryResponse struct {
	Entry                []*ServerEntry `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetServerEntryResponse) Reset()         { *m = GetServerEntryResponse{} }
func (m *GetServerEntryResponse) String() string { return proto.CompactTextString(m) }
func (*GetServerEntryResponse) ProtoMessage()    {}
func (*GetServerEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{5}
}

func (m *GetServerEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServerEntryResponse.Unmarshal(m, b)
}
func (m *GetServerEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServerEntryResponse.Marshal(b, m, deterministic)
}
func (m *GetServerEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServerEntryResponse.Merge(m, src)
}
func (m *GetServerEntryResponse) XXX_Size() int {
	return xxx_messageInfo_GetServerEntryResponse.Size(m)
}
func (m *GetServerEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServerEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServerEntryResponse proto.InternalMessageInfo

func (m *GetServerEntryResponse) GetEntry() []*ServerEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type AddServerEntryRequest struct {
	Entry                *ServerEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddServerEntryRequest) Reset()         { *m = AddServerEntryRequest{} }
func (m *AddServerEntryRequest) String() string { return proto.CompactTextString(m) }
func (*AddServerEntryRequest) ProtoMessage()    {}
func (*AddServerEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{6}
}

func (m *AddServerEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddServerEntryRequest.Unmarshal(m, b)
}
func (m *AddServerEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddServerEntryRequest.Marshal(b, m, deterministic)
}
func (m *AddServerEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddServerEntryRequest.Merge(m, src)
}
func (m *AddServerEntryRequest) XXX_Size() int {
	return xxx_messageInfo_AddServerEntryRequest.Size(m)
}
func (m *AddServerEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddServerEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddServerEntryRequest proto.InternalMessageInfo

func (m *AddServerEntryRequest) GetEntry() *ServerEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type AddServerEntryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddServerEntryResponse) Reset()         { *m = AddServerEntryResponse{} }
func (m *AddServerEntryResponse) String() string { return proto.CompactTextString(m) }
func (*AddServerEntryResponse) ProtoMessage()    {}
func (*AddServerEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{7}
}

func (m *AddServerEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddServerEntryResponse.Unmarshal(m, b)
}
func (m *AddServerEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddServerEntryResponse.Marshal(b, m, deterministic)
}
func (m *AddServerEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddServerEntryResponse.Merge(m, src)
}
func (m *AddServerEntryResponse) XXX_Size() int {
	return xxx_messageInfo_AddServerEntryResponse.Size(m)
}
func (m *AddServerEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddServerEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddServerEntryResponse proto.InternalMessageInfo

type RemoveServerEntryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveServerEntryRequest) Reset()         { *m = RemoveServerEntryRequest{} }
func (m *RemoveServerEntryRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveServerEntryRequest) ProtoMessage()    {}
func (*RemoveServerEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{8}
}

func (m *RemoveServerEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveServerEntryRequest.Unmarshal(m, b)
}
func (m *RemoveServerEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveServerEntryRequest.Marshal(b, m, deterministic)
}
func (m *RemoveServerEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveServerEntryRequest.Merge(m, src)
}
func (m *RemoveServerEntryRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveServerEntryRequest.Size(m)
}
func (m *RemoveServerEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveServerEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveServerEntryRequest proto.InternalMessageInfo

func (m *RemoveServerEntryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RemoveServerEntryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveServerEntryResponse) Reset()         { *m = RemoveServerEntryResponse{} }
func (m *RemoveServerEntryResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveServerEntryResponse) ProtoMessage()    {}
func (*RemoveServerEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{9}
}

func (m *RemoveServerEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveServerEntryResponse.Unmarshal(m, b)
}
func (m *RemoveServerEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveServerEntryResponse.Marshal(b, m, deterministic)
}
func (m *RemoveServerEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveServerEntryResponse.Merge(m, src)
}
func (m *RemoveServerEntryResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveServerEntryResponse.Size(m)
}
func (m *RemoveServerEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveServerEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveServerEntryResponse proto.InternalMessageInfo

//--
// Bungee Entry
//--
type BungeeEntryStream struct {
	Type                 BungeeEntryStream_Type `protobuf:"varint,1,opt,name=type,proto3,enum=nebulapb.BungeeEntryStream_Type" json:"type,omitempty"`
	Entry                *BungeeEntry           `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BungeeEntryStream) Reset()         { *m = BungeeEntryStream{} }
func (m *BungeeEntryStream) String() string { return proto.CompactTextString(m) }
func (*BungeeEntryStream) ProtoMessage()    {}
func (*BungeeEntryStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{10}
}

func (m *BungeeEntryStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BungeeEntryStream.Unmarshal(m, b)
}
func (m *BungeeEntryStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BungeeEntryStream.Marshal(b, m, deterministic)
}
func (m *BungeeEntryStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BungeeEntryStream.Merge(m, src)
}
func (m *BungeeEntryStream) XXX_Size() int {
	return xxx_messageInfo_BungeeEntryStream.Size(m)
}
func (m *BungeeEntryStream) XXX_DiscardUnknown() {
	xxx_messageInfo_BungeeEntryStream.DiscardUnknown(m)
}

var xxx_messageInfo_BungeeEntryStream proto.InternalMessageInfo

func (m *BungeeEntryStream) GetType() BungeeEntryStream_Type {
	if m != nil {
		return m.Type
	}
	return BungeeEntryStream_SYNC
}

func (m *BungeeEntryStream) GetEntry() *BungeeEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type BungeeEntry struct {
	Motd                 string   `protobuf:"bytes,1,opt,name=motd,proto3" json:"motd,omitempty"`
	Favicon              string   `protobuf:"bytes,2,opt,name=favicon,proto3" json:"favicon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BungeeEntry) Reset()         { *m = BungeeEntry{} }
func (m *BungeeEntry) String() string { return proto.CompactTextString(m) }
func (*BungeeEntry) ProtoMessage()    {}
func (*BungeeEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{11}
}

func (m *BungeeEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BungeeEntry.Unmarshal(m, b)
}
func (m *BungeeEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BungeeEntry.Marshal(b, m, deterministic)
}
func (m *BungeeEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BungeeEntry.Merge(m, src)
}
func (m *BungeeEntry) XXX_Size() int {
	return xxx_messageInfo_BungeeEntry.Size(m)
}
func (m *BungeeEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_BungeeEntry.DiscardUnknown(m)
}

var xxx_messageInfo_BungeeEntry proto.InternalMessageInfo

func (m *BungeeEntry) GetMotd() string {
	if m != nil {
		return m.Motd
	}
	return ""
}

func (m *BungeeEntry) GetFavicon() string {
	if m != nil {
		return m.Favicon
	}
	return ""
}

type GetBungeeEntryRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBungeeEntryRequest) Reset()         { *m = GetBungeeEntryRequest{} }
func (m *GetBungeeEntryRequest) String() string { return proto.CompactTextString(m) }
func (*GetBungeeEntryRequest) ProtoMessage()    {}
func (*GetBungeeEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{12}
}

func (m *GetBungeeEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBungeeEntryRequest.Unmarshal(m, b)
}
func (m *GetBungeeEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBungeeEntryRequest.Marshal(b, m, deterministic)
}
func (m *GetBungeeEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBungeeEntryRequest.Merge(m, src)
}
func (m *GetBungeeEntryRequest) XXX_Size() int {
	return xxx_messageInfo_GetBungeeEntryRequest.Size(m)
}
func (m *GetBungeeEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBungeeEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBungeeEntryRequest proto.InternalMessageInfo

type GetBungeeEntryResponse struct {
	Entry                *BungeeEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetBungeeEntryResponse) Reset()         { *m = GetBungeeEntryResponse{} }
func (m *GetBungeeEntryResponse) String() string { return proto.CompactTextString(m) }
func (*GetBungeeEntryResponse) ProtoMessage()    {}
func (*GetBungeeEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{13}
}

func (m *GetBungeeEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBungeeEntryResponse.Unmarshal(m, b)
}
func (m *GetBungeeEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBungeeEntryResponse.Marshal(b, m, deterministic)
}
func (m *GetBungeeEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBungeeEntryResponse.Merge(m, src)
}
func (m *GetBungeeEntryResponse) XXX_Size() int {
	return xxx_messageInfo_GetBungeeEntryResponse.Size(m)
}
func (m *GetBungeeEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBungeeEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBungeeEntryResponse proto.InternalMessageInfo

func (m *GetBungeeEntryResponse) GetEntry() *BungeeEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type SetMotdRequest struct {
	Motd                 string   `protobuf:"bytes,1,opt,name=motd,proto3" json:"motd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMotdRequest) Reset()         { *m = SetMotdRequest{} }
func (m *SetMotdRequest) String() string { return proto.CompactTextString(m) }
func (*SetMotdRequest) ProtoMessage()    {}
func (*SetMotdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{14}
}

func (m *SetMotdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMotdRequest.Unmarshal(m, b)
}
func (m *SetMotdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMotdRequest.Marshal(b, m, deterministic)
}
func (m *SetMotdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMotdRequest.Merge(m, src)
}
func (m *SetMotdRequest) XXX_Size() int {
	return xxx_messageInfo_SetMotdRequest.Size(m)
}
func (m *SetMotdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMotdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMotdRequest proto.InternalMessageInfo

func (m *SetMotdRequest) GetMotd() string {
	if m != nil {
		return m.Motd
	}
	return ""
}

type SetMotdResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMotdResponse) Reset()         { *m = SetMotdResponse{} }
func (m *SetMotdResponse) String() string { return proto.CompactTextString(m) }
func (*SetMotdResponse) ProtoMessage()    {}
func (*SetMotdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{15}
}

func (m *SetMotdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMotdResponse.Unmarshal(m, b)
}
func (m *SetMotdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMotdResponse.Marshal(b, m, deterministic)
}
func (m *SetMotdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMotdResponse.Merge(m, src)
}
func (m *SetMotdResponse) XXX_Size() int {
	return xxx_messageInfo_SetMotdResponse.Size(m)
}
func (m *SetMotdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMotdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMotdResponse proto.InternalMessageInfo

type SetFaviconRequest struct {
	Favicon              string   `protobuf:"bytes,1,opt,name=favicon,proto3" json:"favicon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetFaviconRequest) Reset()         { *m = SetFaviconRequest{} }
func (m *SetFaviconRequest) String() string { return proto.CompactTextString(m) }
func (*SetFaviconRequest) ProtoMessage()    {}
func (*SetFaviconRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{16}
}

func (m *SetFaviconRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetFaviconRequest.Unmarshal(m, b)
}
func (m *SetFaviconRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetFaviconRequest.Marshal(b, m, deterministic)
}
func (m *SetFaviconRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetFaviconRequest.Merge(m, src)
}
func (m *SetFaviconRequest) XXX_Size() int {
	return xxx_messageInfo_SetFaviconRequest.Size(m)
}
func (m *SetFaviconRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetFaviconRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetFaviconRequest proto.InternalMessageInfo

func (m *SetFaviconRequest) GetFavicon() string {
	if m != nil {
		return m.Favicon
	}
	return ""
}

type SetFaviconResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetFaviconResponse) Reset()         { *m = SetFaviconResponse{} }
func (m *SetFaviconResponse) String() string { return proto.CompactTextString(m) }
func (*SetFaviconResponse) ProtoMessage()    {}
func (*SetFaviconResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{17}
}

func (m *SetFaviconResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetFaviconResponse.Unmarshal(m, b)
}
func (m *SetFaviconResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetFaviconResponse.Marshal(b, m, deterministic)
}
func (m *SetFaviconResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetFaviconResponse.Merge(m, src)
}
func (m *SetFaviconResponse) XXX_Size() int {
	return xxx_messageInfo_SetFaviconResponse.Size(m)
}
func (m *SetFaviconResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetFaviconResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetFaviconResponse proto.InternalMessageInfo

type SetLockdownRequest struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lockdown             *Lockdown `protobuf:"bytes,2,opt,name=lockdown,proto3" json:"lockdown,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SetLockdownRequest) Reset()         { *m = SetLockdownRequest{} }
func (m *SetLockdownRequest) String() string { return proto.CompactTextString(m) }
func (*SetLockdownRequest) ProtoMessage()    {}
func (*SetLockdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{18}
}

func (m *SetLockdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLockdownRequest.Unmarshal(m, b)
}
func (m *SetLockdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLockdownRequest.Marshal(b, m, deterministic)
}
func (m *SetLockdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLockdownRequest.Merge(m, src)
}
func (m *SetLockdownRequest) XXX_Size() int {
	return xxx_messageInfo_SetLockdownRequest.Size(m)
}
func (m *SetLockdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLockdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLockdownRequest proto.InternalMessageInfo

func (m *SetLockdownRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetLockdownRequest) GetLockdown() *Lockdown {
	if m != nil {
		return m.Lockdown
	}
	return nil
}

type SetLockdownResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLockdownResponse) Reset()         { *m = SetLockdownResponse{} }
func (m *SetLockdownResponse) String() string { return proto.CompactTextString(m) }
func (*SetLockdownResponse) ProtoMessage()    {}
func (*SetLockdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d182df6f9a02c67f, []int{19}
}

func (m *SetLockdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLockdownResponse.Unmarshal(m, b)
}
func (m *SetLockdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLockdownResponse.Marshal(b, m, deterministic)
}
func (m *SetLockdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLockdownResponse.Merge(m, src)
}
func (m *SetLockdownResponse) XXX_Size() int {
	return xxx_messageInfo_SetLockdownResponse.Size(m)
}
func (m *SetLockdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLockdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetLockdownResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("nebulapb.ServerEntryStream_Type", ServerEntryStream_Type_name, ServerEntryStream_Type_value)
	proto.RegisterEnum("nebulapb.BungeeEntryStream_Type", BungeeEntryStream_Type_name, BungeeEntryStream_Type_value)
	proto.RegisterType((*ServerEntryStream)(nil), "nebulapb.ServerEntryStream")
	proto.RegisterType((*ServerEntry)(nil), "nebulapb.ServerEntry")
	proto.RegisterType((*Lockdown)(nil), "nebulapb.Lockdown")
	proto.RegisterType((*ServerStatus)(nil), "nebulapb.ServerStatus")
	proto.RegisterType((*ServerStatus_Version)(nil), "nebulapb.ServerStatus.Version")
	proto.RegisterType((*ServerStatus_Players)(nil), "nebulapb.ServerStatus.Players")
	proto.RegisterType((*GetServerEntryRequest)(nil), "nebulapb.GetServerEntryRequest")
	proto.RegisterType((*GetServerEntryResponse)(nil), "nebulapb.GetServerEntryResponse")
	proto.RegisterType((*AddServerEntryRequest)(nil), "nebulapb.AddServerEntryRequest")
	proto.RegisterType((*AddServerEntryResponse)(nil), "nebulapb.AddServerEntryResponse")
	proto.RegisterType((*RemoveServerEntryRequest)(nil), "nebulapb.RemoveServerEntryRequest")
	proto.RegisterType((*RemoveServerEntryResponse)(nil), "nebulapb.RemoveServerEntryResponse")
	proto.RegisterType((*BungeeEntryStream)(nil), "nebulapb.BungeeEntryStream")
	proto.RegisterType((*BungeeEntry)(nil), "nebulapb.BungeeEntry")
	proto.RegisterType((*GetBungeeEntryRequest)(nil), "nebulapb.GetBungeeEntryRequest")
	proto.RegisterType((*GetBungeeEntryResponse)(nil), "nebulapb.GetBungeeEntryResponse")
	proto.RegisterType((*SetMotdRequest)(nil), "nebulapb.SetMotdRequest")
	proto.RegisterType((*SetMotdResponse)(nil), "nebulapb.SetMotdResponse")
	proto.RegisterType((*SetFaviconRequest)(nil), "nebulapb.SetFaviconRequest")
	proto.RegisterType((*SetFaviconResponse)(nil), "nebulapb.SetFaviconResponse")
	proto.RegisterType((*SetLockdownRequest)(nil), "nebulapb.SetLockdownRequest")
	proto.RegisterType((*SetLockdownResponse)(nil), "nebulapb.SetLockdownResponse")
}

func init() {
	proto.RegisterFile("nebulapb.proto", fileDescriptor_d182df6f9a02c67f)
}

var fileDescriptor_d182df6f9a02c67f = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x8e, 0xd3, 0x7c, 0xf8, 0x9d, 0x54, 0x79, 0x93, 0x85, 0x04, 0xd7, 0x2d, 0x60, 0x19, 0x0e,
	0x91, 0x10, 0x3e, 0xa4, 0x1c, 0x40, 0x5c, 0xa0, 0x90, 0x22, 0xa4, 0xb6, 0x54, 0x1b, 0xa8, 0xe0,
	0x82, 0xe4, 0xc4, 0x5b, 0x1a, 0xd5, 0xb1, 0x8d, 0xbd, 0x09, 0xe4, 0xc8, 0x8d, 0x1f, 0xc0, 0x6f,
	0x42, 0xfc, 0x2c, 0xb4, 0xeb, 0xb5, 0xb3, 0xfe, 0x08, 0xe9, 0xcd, 0xb3, 0xf3, 0xcc, 0xb3, 0x33,
	0xb3, 0xcf, 0x8c, 0xa1, 0xed, 0x91, 0xc9, 0xc2, 0xb5, 0x83, 0x89, 0x15, 0x84, 0x3e, 0xf5, 0x91,
	0x9a, 0xd8, 0xe6, 0x2f, 0x05, 0xba, 0x63, 0x12, 0x2e, 0x49, 0x38, 0xf2, 0x68, 0xb8, 0x1a, 0xd3,
	0x90, 0xd8, 0x73, 0xf4, 0x04, 0x6a, 0x74, 0x15, 0x10, 0x4d, 0x31, 0x94, 0x41, 0x7b, 0x68, 0x58,
	0x69, 0x78, 0x01, 0x6a, 0xbd, 0x5f, 0x05, 0x04, 0x73, 0x34, 0x7a, 0x04, 0x75, 0xc2, 0x3c, 0x5a,
	0xd5, 0x50, 0x06, 0xad, 0x61, 0xaf, 0x34, 0x0c, 0xc7, 0x18, 0xf3, 0x00, 0x6a, 0x2c, 0x14, 0xa9,
	0x50, 0x1b, 0x7f, 0x3a, 0x7b, 0xd5, 0xa9, 0x20, 0x80, 0x06, 0x1e, 0x9d, 0xbe, 0xbb, 0x18, 0x75,
	0x14, 0xf3, 0x47, 0x15, 0x5a, 0x52, 0x10, 0x42, 0x50, 0xf3, 0xec, 0x79, 0x9c, 0xd0, 0x7f, 0x98,
	0x7f, 0x23, 0x03, 0x5a, 0xce, 0x2c, 0x0a, 0x5c, 0x7b, 0x75, 0xc6, 0x5c, 0x55, 0xee, 0x92, 0x8f,
	0x90, 0x06, 0x4d, 0xdb, 0x71, 0x42, 0x12, 0x45, 0xda, 0x0e, 0xf7, 0x26, 0x26, 0xe3, 0x0b, 0xfc,
	0x90, 0x6a, 0x35, 0x43, 0x19, 0xd4, 0x31, 0xff, 0x66, 0x67, 0x73, 0x9f, 0x3a, 0x5a, 0x3d, 0xbe,
	0x83, 0x7d, 0x23, 0x1d, 0xd4, 0x4b, 0xdb, 0x75, 0x27, 0xf6, 0xf4, 0x5a, 0x6b, 0x18, 0xca, 0x40,
	0xc5, 0xa9, 0x8d, 0x2c, 0x50, 0x5d, 0x7f, 0x7a, 0xed, 0xf8, 0xdf, 0x3c, 0xad, 0xc9, 0x2b, 0x46,
	0xeb, 0x8a, 0x4f, 0x84, 0x07, 0xa7, 0x18, 0x64, 0x41, 0x23, 0xa2, 0x36, 0x5d, 0x44, 0x9a, 0xca,
	0xd1, 0xfd, 0x7c, 0x7f, 0xc6, 0xdc, 0x8b, 0x05, 0xca, 0x3c, 0x06, 0x35, 0x61, 0x61, 0x95, 0x10,
	0xcf, 0x9e, 0xb8, 0xc4, 0xe1, 0x2d, 0x50, 0x71, 0x62, 0xf2, 0x2e, 0x90, 0x68, 0x1a, 0xce, 0x02,
	0x3a, 0xf3, 0xbd, 0xb4, 0x0b, 0xeb, 0x23, 0xf3, 0x77, 0x15, 0x76, 0xe5, 0x0b, 0x50, 0x1f, 0x1a,
	0xbe, 0xe7, 0xce, 0x3c, 0x22, 0xb8, 0x84, 0x85, 0x9e, 0x42, 0x73, 0x49, 0xc2, 0x28, 0xa1, 0x69,
	0x0d, 0xef, 0x95, 0x67, 0x68, 0x5d, 0xc4, 0x28, 0x9c, 0xc0, 0x59, 0x24, 0x6b, 0x3a, 0x09, 0xe3,
	0x46, 0x6f, 0x8e, 0x3c, 0x8f, 0x51, 0x38, 0x81, 0xe7, 0xd3, 0xaf, 0x15, 0xd2, 0x67, 0xa5, 0x5f,
	0xda, 0xcb, 0xd9, 0xd4, 0xf7, 0xc4, 0xcb, 0x24, 0xa6, 0xfe, 0x0c, 0x9a, 0x22, 0x93, 0x52, 0x7d,
	0xe8, 0xa0, 0x72, 0xb5, 0x4f, 0x7d, 0x97, 0xd7, 0x53, 0xc7, 0xa9, 0xad, 0x1f, 0x42, 0x53, 0xa4,
	0x82, 0x3a, 0xb0, 0x33, 0xb7, 0xbf, 0xf3, 0xc8, 0x3a, 0x66, 0x9f, 0x52, 0x7f, 0xe2, 0x30, 0x61,
	0x99, 0x77, 0xa0, 0xf7, 0x86, 0x50, 0x59, 0xcb, 0xe4, 0xeb, 0x82, 0x44, 0xd4, 0x1c, 0x41, 0x3f,
	0xef, 0x88, 0x02, 0xdf, 0x8b, 0xa4, 0x91, 0x50, 0x8c, 0x9d, 0xad, 0x23, 0xf1, 0x1a, 0x7a, 0x2f,
	0x1d, 0xa7, 0xc8, 0x2f, 0xb3, 0x6c, 0x1f, 0x2c, 0x0d, 0xfa, 0x79, 0x96, 0x38, 0x19, 0xd3, 0x02,
	0x0d, 0x93, 0xb9, 0xbf, 0x24, 0x25, 0x57, 0x94, 0x34, 0xd0, 0xdc, 0x87, 0xbd, 0x12, 0xbc, 0x20,
	0xfb, 0xa9, 0x40, 0xf7, 0x68, 0xe1, 0x7d, 0x21, 0xe4, 0x46, 0x8b, 0xa3, 0x00, 0xbd, 0xd9, 0xe2,
	0x90, 0xc2, 0x92, 0xfa, 0x3a, 0xf9, 0xc5, 0x61, 0x3e, 0x87, 0x96, 0x84, 0x4b, 0xe7, 0x58, 0x91,
	0xe6, 0x58, 0x12, 0x51, 0x35, 0x23, 0x22, 0xf1, 0xa8, 0xf2, 0x3d, 0x99, 0x47, 0xcd, 0x38, 0x8a,
	0x8f, 0xba, 0x3d, 0xdd, 0x87, 0xd0, 0x1e, 0x13, 0x7a, 0xea, 0x53, 0x47, 0x6a, 0x75, 0x3e, 0x3f,
	0xb3, 0x0b, 0xff, 0xa7, 0x28, 0xd1, 0xe0, 0xc7, 0x6c, 0x31, 0xd3, 0xe3, 0x38, 0xcd, 0x24, 0x56,
	0xaa, 0x43, 0xc9, 0xd6, 0x71, 0x1b, 0x90, 0x0c, 0x17, 0x24, 0x1f, 0xf9, 0x69, 0xba, 0x8c, 0x36,
	0x3f, 0x76, 0x66, 0x9b, 0x55, 0xb7, 0x6f, 0x33, 0xb3, 0x07, 0xb7, 0x32, 0xcc, 0xf1, 0x85, 0xc3,
	0x3f, 0x35, 0x68, 0x9c, 0xf1, 0x30, 0xf4, 0x01, 0xda, 0xd9, 0xa9, 0x40, 0xf7, 0xd7, 0x8c, 0xa5,
	0x83, 0xa4, 0x1b, 0x9b, 0x01, 0xa2, 0xa0, 0x0a, 0xa3, 0xcd, 0xea, 0x5b, 0xa6, 0x2d, 0x9d, 0x1f,
	0x99, 0x76, 0xc3, 0x68, 0x54, 0xd0, 0x67, 0xe8, 0x16, 0xc4, 0x8e, 0xcc, 0x75, 0xe0, 0xa6, 0xc9,
	0xd1, 0x1f, 0xfc, 0x13, 0x23, 0xa7, 0x9d, 0x95, 0x53, 0xae, 0x1b, 0x45, 0x05, 0xe6, 0xba, 0x51,
	0xa2, 0x44, 0xb3, 0x82, 0x5e, 0x40, 0x53, 0x08, 0x07, 0x69, 0xf2, 0x5a, 0x90, 0x15, 0xa7, 0xef,
	0x95, 0x78, 0x52, 0x86, 0xb7, 0x00, 0x6b, 0xe1, 0xa0, 0xfd, 0x0c, 0x34, 0xab, 0x3e, 0xfd, 0xa0,
	0xdc, 0x99, 0x52, 0x9d, 0xb0, 0x9f, 0x76, 0xaa, 0x09, 0x94, 0x85, 0xe7, 0x44, 0xa8, 0xdf, 0xdd,
	0xe0, 0x4d, 0xd8, 0x8e, 0x06, 0xa0, 0x79, 0x84, 0x5a, 0xd1, 0xca, 0x9b, 0x5e, 0xd1, 0xab, 0x99,
	0x6d, 0xd9, 0xc1, 0x4c, 0xc4, 0x1c, 0xed, 0xc6, 0x1a, 0x3b, 0x67, 0xfb, 0x3c, 0x9a, 0x34, 0xf8,
	0x5e, 0x3f, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xb2, 0xdb, 0xaf, 0xe7, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NebulaClient is the client API for Nebula service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NebulaClient interface {
	// API -> Bungee (ServerEntry)
	GetServerEntry(ctx context.Context, in *GetServerEntryRequest, opts ...grpc.CallOption) (*GetServerEntryResponse, error)
	// API <- App
	AddServerEntry(ctx context.Context, in *AddServerEntryRequest, opts ...grpc.CallOption) (*AddServerEntryResponse, error)
	// API <- App
	RemoveServerEntry(ctx context.Context, in *RemoveServerEntryRequest, opts ...grpc.CallOption) (*RemoveServerEntryResponse, error)
	// API -> Bungee (BungeeEntry)
	GetBungeeEntry(ctx context.Context, in *GetBungeeEntryRequest, opts ...grpc.CallOption) (*GetBungeeEntryResponse, error)
	// API <- App
	SetMotd(ctx context.Context, in *SetMotdRequest, opts ...grpc.CallOption) (*SetMotdResponse, error)
	// API <- App
	SetFavicon(ctx context.Context, in *SetFaviconRequest, opts ...grpc.CallOption) (*SetFaviconResponse, error)
	// API <- App
	SetLockdown(ctx context.Context, in *SetLockdownRequest, opts ...grpc.CallOption) (*SetLockdownResponse, error)
}

type nebulaClient struct {
	cc grpc.ClientConnInterface
}

func NewNebulaClient(cc grpc.ClientConnInterface) NebulaClient {
	return &nebulaClient{cc}
}

func (c *nebulaClient) GetServerEntry(ctx context.Context, in *GetServerEntryRequest, opts ...grpc.CallOption) (*GetServerEntryResponse, error) {
	out := new(GetServerEntryResponse)
	err := c.cc.Invoke(ctx, "/nebulapb.Nebula/GetServerEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaClient) AddServerEntry(ctx context.Context, in *AddServerEntryRequest, opts ...grpc.CallOption) (*AddServerEntryResponse, error) {
	out := new(AddServerEntryResponse)
	err := c.cc.Invoke(ctx, "/nebulapb.Nebula/AddServerEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaClient) RemoveServerEntry(ctx context.Context, in *RemoveServerEntryRequest, opts ...grpc.CallOption) (*RemoveServerEntryResponse, error) {
	out := new(RemoveServerEntryResponse)
	err := c.cc.Invoke(ctx, "/nebulapb.Nebula/RemoveServerEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaClient) GetBungeeEntry(ctx context.Context, in *GetBungeeEntryRequest, opts ...grpc.CallOption) (*GetBungeeEntryResponse, error) {
	out := new(GetBungeeEntryResponse)
	err := c.cc.Invoke(ctx, "/nebulapb.Nebula/GetBungeeEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaClient) SetMotd(ctx context.Context, in *SetMotdRequest, opts ...grpc.CallOption) (*SetMotdResponse, error) {
	out := new(SetMotdResponse)
	err := c.cc.Invoke(ctx, "/nebulapb.Nebula/SetMotd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaClient) SetFavicon(ctx context.Context, in *SetFaviconRequest, opts ...grpc.CallOption) (*SetFaviconResponse, error) {
	out := new(SetFaviconResponse)
	err := c.cc.Invoke(ctx, "/nebulapb.Nebula/SetFavicon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaClient) SetLockdown(ctx context.Context, in *SetLockdownRequest, opts ...grpc.CallOption) (*SetLockdownResponse, error) {
	out := new(SetLockdownResponse)
	err := c.cc.Invoke(ctx, "/nebulapb.Nebula/SetLockdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NebulaServer is the server API for Nebula service.
type NebulaServer interface {
	// API -> Bungee (ServerEntry)
	GetServerEntry(context.Context, *GetServerEntryRequest) (*GetServerEntryResponse, error)
	// API <- App
	AddServerEntry(context.Context, *AddServerEntryRequest) (*AddServerEntryResponse, error)
	// API <- App
	RemoveServerEntry(context.Context, *RemoveServerEntryRequest) (*RemoveServerEntryResponse, error)
	// API -> Bungee (BungeeEntry)
	GetBungeeEntry(context.Context, *GetBungeeEntryRequest) (*GetBungeeEntryResponse, error)
	// API <- App
	SetMotd(context.Context, *SetMotdRequest) (*SetMotdResponse, error)
	// API <- App
	SetFavicon(context.Context, *SetFaviconRequest) (*SetFaviconResponse, error)
	// API <- App
	SetLockdown(context.Context, *SetLockdownRequest) (*SetLockdownResponse, error)
}

// UnimplementedNebulaServer can be embedded to have forward compatible implementations.
type UnimplementedNebulaServer struct {
}

func (*UnimplementedNebulaServer) GetServerEntry(ctx context.Context, req *GetServerEntryRequest) (*GetServerEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerEntry not implemented")
}
func (*UnimplementedNebulaServer) AddServerEntry(ctx context.Context, req *AddServerEntryRequest) (*AddServerEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddServerEntry not implemented")
}
func (*UnimplementedNebulaServer) RemoveServerEntry(ctx context.Context, req *RemoveServerEntryRequest) (*RemoveServerEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveServerEntry not implemented")
}
func (*UnimplementedNebulaServer) GetBungeeEntry(ctx context.Context, req *GetBungeeEntryRequest) (*GetBungeeEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBungeeEntry not implemented")
}
func (*UnimplementedNebulaServer) SetMotd(ctx context.Context, req *SetMotdRequest) (*SetMotdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMotd not implemented")
}
func (*UnimplementedNebulaServer) SetFavicon(ctx context.Context, req *SetFaviconRequest) (*SetFaviconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFavicon not implemented")
}
func (*UnimplementedNebulaServer) SetLockdown(ctx context.Context, req *SetLockdownRequest) (*SetLockdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLockdown not implemented")
}

func RegisterNebulaServer(s *grpc.Server, srv NebulaServer) {
	s.RegisterService(&_Nebula_serviceDesc, srv)
}

func _Nebula_GetServerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).GetServerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebulapb.Nebula/GetServerEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).GetServerEntry(ctx, req.(*GetServerEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nebula_AddServerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServerEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).AddServerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebulapb.Nebula/AddServerEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).AddServerEntry(ctx, req.(*AddServerEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nebula_RemoveServerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveServerEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).RemoveServerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebulapb.Nebula/RemoveServerEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).RemoveServerEntry(ctx, req.(*RemoveServerEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nebula_GetBungeeEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBungeeEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).GetBungeeEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebulapb.Nebula/GetBungeeEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).GetBungeeEntry(ctx, req.(*GetBungeeEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nebula_SetMotd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMotdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).SetMotd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebulapb.Nebula/SetMotd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).SetMotd(ctx, req.(*SetMotdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nebula_SetFavicon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFaviconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).SetFavicon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebulapb.Nebula/SetFavicon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).SetFavicon(ctx, req.(*SetFaviconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nebula_SetLockdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLockdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).SetLockdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebulapb.Nebula/SetLockdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).SetLockdown(ctx, req.(*SetLockdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nebula_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nebulapb.Nebula",
	HandlerType: (*NebulaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerEntry",
			Handler:    _Nebula_GetServerEntry_Handler,
		},
		{
			MethodName: "AddServerEntry",
			Handler:    _Nebula_AddServerEntry_Handler,
		},
		{
			MethodName: "RemoveServerEntry",
			Handler:    _Nebula_RemoveServerEntry_Handler,
		},
		{
			MethodName: "GetBungeeEntry",
			Handler:    _Nebula_GetBungeeEntry_Handler,
		},
		{
			MethodName: "SetMotd",
			Handler:    _Nebula_SetMotd_Handler,
		},
		{
			MethodName: "SetFavicon",
			Handler:    _Nebula_SetFavicon_Handler,
		},
		{
			MethodName: "SetLockdown",
			Handler:    _Nebula_SetLockdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nebulapb.proto",
}
