// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nebulapb.proto

/*
Package nebulapb is a generated protocol buffer package.

It is generated from these files:
	nebulapb.proto

It has these top-level messages:
	ServerEntryStream
	ServerEntry
	ServerStatus
	GetServerEntryRequest
	GetServerEntryResponse
	AddServerEntryRequest
	AddServerEntryResponse
	RemoveServerEntryRequest
	RemoveServerEntryResponse
*/
package nebulapb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerEntryStream_Type int32

const (
	ServerEntryStream_SYNC   ServerEntryStream_Type = 0
	ServerEntryStream_REMOVE ServerEntryStream_Type = 1
)

var ServerEntryStream_Type_name = map[int32]string{
	0: "SYNC",
	1: "REMOVE",
}
var ServerEntryStream_Type_value = map[string]int32{
	"SYNC":   0,
	"REMOVE": 1,
}

func (x ServerEntryStream_Type) String() string {
	return proto.EnumName(ServerEntryStream_Type_name, int32(x))
}
func (ServerEntryStream_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// ServerEntryStream (type: sync, remove)
type ServerEntryStream struct {
	Type  ServerEntryStream_Type `protobuf:"varint,1,opt,name=type,enum=nebulapb.ServerEntryStream_Type" json:"type,omitempty"`
	Entry *ServerEntry           `protobuf:"bytes,2,opt,name=entry" json:"entry,omitempty"`
}

func (m *ServerEntryStream) Reset()                    { *m = ServerEntryStream{} }
func (m *ServerEntryStream) String() string            { return proto.CompactTextString(m) }
func (*ServerEntryStream) ProtoMessage()               {}
func (*ServerEntryStream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServerEntryStream) GetType() ServerEntryStream_Type {
	if m != nil {
		return m.Type
	}
	return ServerEntryStream_SYNC
}

func (m *ServerEntryStream) GetEntry() *ServerEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type ServerEntry struct {
	Name        string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DisplayName string        `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty"`
	Address     string        `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Port        int32         `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	Motd        string        `protobuf:"bytes,5,opt,name=motd" json:"motd,omitempty"`
	Fallback    bool          `protobuf:"varint,6,opt,name=fallback" json:"fallback,omitempty"`
	Status      *ServerStatus `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
}

func (m *ServerEntry) Reset()                    { *m = ServerEntry{} }
func (m *ServerEntry) String() string            { return proto.CompactTextString(m) }
func (*ServerEntry) ProtoMessage()               {}
func (*ServerEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerEntry) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ServerEntry) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ServerEntry) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerEntry) GetMotd() string {
	if m != nil {
		return m.Motd
	}
	return ""
}

func (m *ServerEntry) GetFallback() bool {
	if m != nil {
		return m.Fallback
	}
	return false
}

func (m *ServerEntry) GetStatus() *ServerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ServerStatus struct {
	Online  bool                  `protobuf:"varint,1,opt,name=online" json:"online,omitempty"`
	Version *ServerStatus_Version `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Players *ServerStatus_Players `protobuf:"bytes,3,opt,name=players" json:"players,omitempty"`
	// i don't have any idea... (need map)
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Favicon     string `protobuf:"bytes,5,opt,name=favicon" json:"favicon,omitempty"`
}

func (m *ServerStatus) Reset()                    { *m = ServerStatus{} }
func (m *ServerStatus) String() string            { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()               {}
func (*ServerStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServerStatus) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *ServerStatus) GetVersion() *ServerStatus_Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ServerStatus) GetPlayers() *ServerStatus_Players {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *ServerStatus) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ServerStatus) GetFavicon() string {
	if m != nil {
		return m.Favicon
	}
	return ""
}

type ServerStatus_Version struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Protocol int32  `protobuf:"varint,2,opt,name=protocol" json:"protocol,omitempty"`
}

func (m *ServerStatus_Version) Reset()                    { *m = ServerStatus_Version{} }
func (m *ServerStatus_Version) String() string            { return proto.CompactTextString(m) }
func (*ServerStatus_Version) ProtoMessage()               {}
func (*ServerStatus_Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *ServerStatus_Version) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerStatus_Version) GetProtocol() int32 {
	if m != nil {
		return m.Protocol
	}
	return 0
}

type ServerStatus_Players struct {
	Max    int32 `protobuf:"varint,1,opt,name=max" json:"max,omitempty"`
	Online int32 `protobuf:"varint,2,opt,name=online" json:"online,omitempty"`
}

func (m *ServerStatus_Players) Reset()                    { *m = ServerStatus_Players{} }
func (m *ServerStatus_Players) String() string            { return proto.CompactTextString(m) }
func (*ServerStatus_Players) ProtoMessage()               {}
func (*ServerStatus_Players) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *ServerStatus_Players) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *ServerStatus_Players) GetOnline() int32 {
	if m != nil {
		return m.Online
	}
	return 0
}

//
// ServerEntry
//
type GetServerEntryRequest struct {
}

func (m *GetServerEntryRequest) Reset()                    { *m = GetServerEntryRequest{} }
func (m *GetServerEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*GetServerEntryRequest) ProtoMessage()               {}
func (*GetServerEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetServerEntryResponse struct {
	Entry []*ServerEntry `protobuf:"bytes,1,rep,name=entry" json:"entry,omitempty"`
}

func (m *GetServerEntryResponse) Reset()                    { *m = GetServerEntryResponse{} }
func (m *GetServerEntryResponse) String() string            { return proto.CompactTextString(m) }
func (*GetServerEntryResponse) ProtoMessage()               {}
func (*GetServerEntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetServerEntryResponse) GetEntry() []*ServerEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type AddServerEntryRequest struct {
	Entry *ServerEntry `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
}

func (m *AddServerEntryRequest) Reset()                    { *m = AddServerEntryRequest{} }
func (m *AddServerEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*AddServerEntryRequest) ProtoMessage()               {}
func (*AddServerEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AddServerEntryRequest) GetEntry() *ServerEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type AddServerEntryResponse struct {
}

func (m *AddServerEntryResponse) Reset()                    { *m = AddServerEntryResponse{} }
func (m *AddServerEntryResponse) String() string            { return proto.CompactTextString(m) }
func (*AddServerEntryResponse) ProtoMessage()               {}
func (*AddServerEntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type RemoveServerEntryRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *RemoveServerEntryRequest) Reset()                    { *m = RemoveServerEntryRequest{} }
func (m *RemoveServerEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveServerEntryRequest) ProtoMessage()               {}
func (*RemoveServerEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RemoveServerEntryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RemoveServerEntryResponse struct {
}

func (m *RemoveServerEntryResponse) Reset()                    { *m = RemoveServerEntryResponse{} }
func (m *RemoveServerEntryResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveServerEntryResponse) ProtoMessage()               {}
func (*RemoveServerEntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*ServerEntryStream)(nil), "nebulapb.ServerEntryStream")
	proto.RegisterType((*ServerEntry)(nil), "nebulapb.ServerEntry")
	proto.RegisterType((*ServerStatus)(nil), "nebulapb.ServerStatus")
	proto.RegisterType((*ServerStatus_Version)(nil), "nebulapb.ServerStatus.Version")
	proto.RegisterType((*ServerStatus_Players)(nil), "nebulapb.ServerStatus.Players")
	proto.RegisterType((*GetServerEntryRequest)(nil), "nebulapb.GetServerEntryRequest")
	proto.RegisterType((*GetServerEntryResponse)(nil), "nebulapb.GetServerEntryResponse")
	proto.RegisterType((*AddServerEntryRequest)(nil), "nebulapb.AddServerEntryRequest")
	proto.RegisterType((*AddServerEntryResponse)(nil), "nebulapb.AddServerEntryResponse")
	proto.RegisterType((*RemoveServerEntryRequest)(nil), "nebulapb.RemoveServerEntryRequest")
	proto.RegisterType((*RemoveServerEntryResponse)(nil), "nebulapb.RemoveServerEntryResponse")
	proto.RegisterEnum("nebulapb.ServerEntryStream_Type", ServerEntryStream_Type_name, ServerEntryStream_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Nebula service

type NebulaClient interface {
	// API -> Bungee (ServerEntry)
	GetServerEntry(ctx context.Context, in *GetServerEntryRequest, opts ...grpc.CallOption) (*GetServerEntryResponse, error)
	// API <- App
	AddServerEntry(ctx context.Context, in *AddServerEntryRequest, opts ...grpc.CallOption) (*AddServerEntryResponse, error)
	// API <- App
	RemoveServerEntry(ctx context.Context, in *RemoveServerEntryRequest, opts ...grpc.CallOption) (*RemoveServerEntryResponse, error)
}

type nebulaClient struct {
	cc *grpc.ClientConn
}

func NewNebulaClient(cc *grpc.ClientConn) NebulaClient {
	return &nebulaClient{cc}
}

func (c *nebulaClient) GetServerEntry(ctx context.Context, in *GetServerEntryRequest, opts ...grpc.CallOption) (*GetServerEntryResponse, error) {
	out := new(GetServerEntryResponse)
	err := grpc.Invoke(ctx, "/nebulapb.Nebula/GetServerEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaClient) AddServerEntry(ctx context.Context, in *AddServerEntryRequest, opts ...grpc.CallOption) (*AddServerEntryResponse, error) {
	out := new(AddServerEntryResponse)
	err := grpc.Invoke(ctx, "/nebulapb.Nebula/AddServerEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaClient) RemoveServerEntry(ctx context.Context, in *RemoveServerEntryRequest, opts ...grpc.CallOption) (*RemoveServerEntryResponse, error) {
	out := new(RemoveServerEntryResponse)
	err := grpc.Invoke(ctx, "/nebulapb.Nebula/RemoveServerEntry", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Nebula service

type NebulaServer interface {
	// API -> Bungee (ServerEntry)
	GetServerEntry(context.Context, *GetServerEntryRequest) (*GetServerEntryResponse, error)
	// API <- App
	AddServerEntry(context.Context, *AddServerEntryRequest) (*AddServerEntryResponse, error)
	// API <- App
	RemoveServerEntry(context.Context, *RemoveServerEntryRequest) (*RemoveServerEntryResponse, error)
}

func RegisterNebulaServer(s *grpc.Server, srv NebulaServer) {
	s.RegisterService(&_Nebula_serviceDesc, srv)
}

func _Nebula_GetServerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).GetServerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebulapb.Nebula/GetServerEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).GetServerEntry(ctx, req.(*GetServerEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nebula_AddServerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServerEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).AddServerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebulapb.Nebula/AddServerEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).AddServerEntry(ctx, req.(*AddServerEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nebula_RemoveServerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveServerEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaServer).RemoveServerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nebulapb.Nebula/RemoveServerEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaServer).RemoveServerEntry(ctx, req.(*RemoveServerEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nebula_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nebulapb.Nebula",
	HandlerType: (*NebulaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerEntry",
			Handler:    _Nebula_GetServerEntry_Handler,
		},
		{
			MethodName: "AddServerEntry",
			Handler:    _Nebula_AddServerEntry_Handler,
		},
		{
			MethodName: "RemoveServerEntry",
			Handler:    _Nebula_RemoveServerEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nebulapb.proto",
}

func init() { proto.RegisterFile("nebulapb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0xa5, 0x50, 0x4a, 0xbd, 0x6c, 0x08, 0x3b, 0x09, 0x38, 0x56, 0xa3, 0x4d, 0x7d, 0x21, 0x31,
	0xe9, 0x03, 0xeb, 0x83, 0x3e, 0xba, 0x4a, 0x7c, 0x12, 0x37, 0x83, 0x6e, 0xe2, 0x8b, 0xc9, 0x40,
	0x67, 0xb3, 0x8d, 0xa5, 0xad, 0x9d, 0x81, 0xd8, 0xff, 0x61, 0xfc, 0x49, 0xbe, 0xfb, 0x8f, 0xcc,
	0x7c, 0x14, 0xba, 0x50, 0x76, 0xdf, 0xee, 0xed, 0x3d, 0xe7, 0xcc, 0x3d, 0xa7, 0x17, 0x06, 0x29,
	0x5b, 0x6e, 0x12, 0x9a, 0x2f, 0xc3, 0xbc, 0xc8, 0x44, 0x86, 0xdc, 0xaa, 0x0f, 0x7e, 0x5b, 0x70,
	0xbe, 0x60, 0xc5, 0x96, 0x15, 0xb3, 0x54, 0x14, 0xe5, 0x42, 0x14, 0x8c, 0xae, 0xd1, 0x6b, 0xb0,
	0x45, 0x99, 0x33, 0x6c, 0xf9, 0xd6, 0x64, 0x30, 0xf5, 0xc3, 0x1d, 0xfd, 0x08, 0x1a, 0x7e, 0x29,
	0x73, 0x46, 0x14, 0x1a, 0xbd, 0x82, 0x2e, 0x93, 0x13, 0xdc, 0xf6, 0xad, 0x49, 0x7f, 0x3a, 0x6a,
	0xa4, 0x11, 0x8d, 0x09, 0x9e, 0x81, 0x2d, 0xa9, 0xc8, 0x05, 0x7b, 0xf1, 0x6d, 0xfe, 0x7e, 0xd8,
	0x42, 0x00, 0x0e, 0x99, 0x7d, 0xfa, 0x7c, 0x3d, 0x1b, 0x5a, 0xc1, 0x3f, 0x0b, 0xfa, 0x35, 0x12,
	0x42, 0x60, 0xa7, 0x74, 0xad, 0x17, 0x7a, 0x44, 0x54, 0x8d, 0x7c, 0xe8, 0x47, 0x31, 0xcf, 0x13,
	0x5a, 0xce, 0xe5, 0xa8, 0xad, 0x46, 0xf5, 0x4f, 0x08, 0x43, 0x8f, 0x46, 0x51, 0xc1, 0x38, 0xc7,
	0x1d, 0x35, 0xad, 0x5a, 0xa9, 0x97, 0x67, 0x85, 0xc0, 0xb6, 0x6f, 0x4d, 0xba, 0x44, 0xd5, 0xf2,
	0xdb, 0x3a, 0x13, 0x11, 0xee, 0xea, 0x37, 0x64, 0x8d, 0x3c, 0x70, 0x6f, 0x68, 0x92, 0x2c, 0xe9,
	0xea, 0x07, 0x76, 0x7c, 0x6b, 0xe2, 0x92, 0x5d, 0x8f, 0x42, 0x70, 0xb8, 0xa0, 0x62, 0xc3, 0x71,
	0x4f, 0xf9, 0x1d, 0x1f, 0xfa, 0x5d, 0xa8, 0x29, 0x31, 0xa8, 0xe0, 0x6f, 0x1b, 0xce, 0xea, 0x03,
	0x34, 0x06, 0x27, 0x4b, 0x93, 0x38, 0xd5, 0xb6, 0x5c, 0x62, 0x3a, 0xf4, 0x06, 0x7a, 0x5b, 0x56,
	0xf0, 0x38, 0x4b, 0x4d, 0x92, 0xcf, 0x9b, 0x95, 0xc3, 0x6b, 0x8d, 0x22, 0x15, 0x5c, 0x32, 0xa5,
	0x79, 0x56, 0x68, 0xc3, 0xa7, 0x99, 0x57, 0x1a, 0x45, 0x2a, 0xb8, 0x0a, 0x93, 0xf1, 0x55, 0x11,
	0xe7, 0x42, 0xbe, 0x6b, 0x9b, 0x30, 0xf7, 0x9f, 0x64, 0x98, 0x37, 0x74, 0x1b, 0xaf, 0xb2, 0xd4,
	0x24, 0x54, 0xb5, 0xde, 0x5b, 0xe8, 0x99, 0x4d, 0x1a, 0xff, 0x93, 0x07, 0xae, 0xba, 0xba, 0x55,
	0x96, 0x28, 0x3f, 0x5d, 0xb2, 0xeb, 0xbd, 0x0b, 0xe8, 0x99, 0x55, 0xd0, 0x10, 0x3a, 0x6b, 0xfa,
	0x4b, 0x31, 0xbb, 0x44, 0x96, 0xb5, 0x7c, 0x34, 0xcd, 0x74, 0xc1, 0x63, 0x18, 0x7d, 0x64, 0xa2,
	0x7e, 0x53, 0xec, 0xe7, 0x86, 0x71, 0x11, 0xcc, 0x60, 0x7c, 0x38, 0xe0, 0x79, 0x96, 0xf2, 0xda,
	0x69, 0x5a, 0x7e, 0xe7, 0xc1, 0xd3, 0xfc, 0x00, 0xa3, 0x77, 0x51, 0x74, 0xac, 0x5f, 0x57, 0x79,
	0xf8, 0xc0, 0x31, 0x8c, 0x0f, 0x55, 0xf4, 0x32, 0x41, 0x08, 0x98, 0xb0, 0x75, 0xb6, 0x65, 0x0d,
	0x4f, 0x34, 0x04, 0x18, 0x3c, 0x85, 0x27, 0x0d, 0x78, 0x2d, 0x36, 0xfd, 0xd3, 0x06, 0x67, 0xae,
	0xd6, 0x40, 0x5f, 0x61, 0x70, 0xd7, 0x3e, 0x7a, 0xb1, 0xdf, 0xb0, 0x31, 0x31, 0xcf, 0x3f, 0x0d,
	0x30, 0xcb, 0xb6, 0xa4, 0xec, 0x5d, 0x23, 0x75, 0xd9, 0xc6, 0xa0, 0xea, 0xb2, 0x27, 0x32, 0x68,
	0xa1, 0xef, 0x70, 0x7e, 0xe4, 0x0a, 0x05, 0x7b, 0xe2, 0xa9, 0x88, 0xbc, 0x97, 0xf7, 0x62, 0x2a,
	0xfd, 0xcb, 0x09, 0xe0, 0x94, 0x89, 0x90, 0x97, 0xe9, 0xea, 0x56, 0xdc, 0xc6, 0x34, 0xa4, 0x79,
	0x6c, 0x98, 0x97, 0x67, 0x3a, 0xb1, 0x2b, 0x79, 0x86, 0x7c, 0xe9, 0xa8, 0x73, 0xbc, 0xf8, 0x1f,
	0x00, 0x00, 0xff, 0xff, 0xbb, 0x01, 0xf4, 0xfb, 0x26, 0x05, 0x00, 0x00,
}
